# Generated by Django 5.0.3 on 2024-03-08 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(blank=True, max_length=100, null=True)),
                ('Email', models.EmailField(max_length=254)),
                ('Telefone', models.IntegerField()),
                ('Mensagem', models.TextField(max_length=500)),
                ('Lido', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Contatos',
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Newsletter',
            },
        ),
    ]
