# Generated by Django 4.0.2 on 2024-03-09 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_contato_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='promocao',
            field=models.BooleanField(default=False),
        ),
    ]
